services:
  frontend:
    image: paypaw/frontend:latest
    networks:
      - proxy
  backend:
    image: paypaw/backend:latest
    networks:
      - proxy
    environment:
      JWT_SECRET: supersecret
      JWT_ALG: HS256
      REFRESH_TOKEN_TTL_SEC: 1800
      ACCESS_TOKEN_TTL_SEC: 2592000
      VERIFICATION_TOKEN_TTL_SEC: 1800
      DOMAIN: ${DOMAIN_API}
      DEV: TRUE
      MONGODB__CONNECTION_URI: mongodb://${MONGODB_USER}:${MONGODB_PASS}@${MONGODB_ADDR}
      MONGODB__DATABASE: cryptopay
      MONGODB__TIMOUTMS: 10000
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - proxy
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
  traefik:
    image: traefik:v3.5.0
    networks:
      - proxy
    command:
      - --api.dashboard=true
      - --accesslog=true
      - --log.level=DEBUG
      - --entrypoints.web.address=:80
      - --entrypoints.web.asDefault=true
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.asDefault=true
      # - --entrypoints.websecure.http.tls=true
      - --entryPoints.web.http.redirections.entryPoint.to=websecure
      - --entryPoints.web.http.redirections.entryPoint.scheme=https
      # PROVIDERS
      - --providers.file.directory=/etc/traefik/dynamic_config
      - --providers.file.watch=true
      # SSL
      - --certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.myresolver.acme.storage=/le/acme.json
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
    environment:
      - DOMAIN_API
      - DOMAIN_WEB
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./le:/le
      - ./dynamic_config:/etc/traefik/dynamic_config:ro
networks:
  proxy:
    name: proxy
