http:
  middlewares:
    auth:
      basicAuth:
        users:
          - "user:$2b$05$M9ZME5HpkEimIScVddG5geJLDvwAdn7.GCDheaHmEqJNWf3o3V4KW"
  routers:
    backend:
      rule: Host(`{{env "DOMAIN_API"}}`)
      service: backend
      middlewares:
        - auth
      tls:
        certResolver: myresolver

    frontend:
      rule: Host(`{{env "DOMAIN_WEB"}}`)
      service: frontend
      middlewares:
        - auth
      tls:
        certResolver: myresolver

  services:
    backend:
      loadBalancer:
        servers:
          - url: "http://backend:8000"

    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:3000"
